name: inventario_app_nuevo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # AÑADIDO - CRÍTICO para MaterialLocalizations
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.13

  # Lanzar URLs
  url_launcher: ^6.3.0

  # Base de datos local
  sqflite: ^2.4.1
  path: ^1.9.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  cloud_firestore: ^5.6.12

  # Conectividad y almacenamiento local
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2

  # Utilidades
  uuid: ^4.5.1
  intl: 0.20.2  # CAMBIADO: versión más compatible

  # Códigos de barras y QR
  barcode: ^2.2.9
  mobile_scanner: ^6.0.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true